version: '3.7'

services:
  loveDb:
    image: mariadb:10
    ports:
      - 3307:3306
    volumes:
      - /mnt/loveDb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=lei123
      - MYSQL_DATABASE=lei
    restart: always
    command: '--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
  loveRedis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379