version: '3.7'
services:
  # traefik:
  #   image: traefik:latest
  #   ports:
  #     - 443:443
  #     - 80:80
  # frontend:
  #   image: nginx:latest
  #   ports:
  #     - 5001:80
  #   volumes:
  #     - /home/lei/workspace/flask_lovehome/frontend/dist:/usr/share/nginx/html
  #   restart: always
  backend_1:
    build: ./
    image: lovehome:1.0
    volumes:
      - ./:/workspace/lovehome
    ports:
      - 5000:5000
    networks:
      - lovedb
    depends_on:
      - loveDb
      - loveRedis
    command: run -h 0.0.0.0 -p 5000
    depends_on:
      - loveDb
      - loveRedis
    environment:
      - USERNAME=root
      - PASSWORD=lei123
      - HOST=loveDb
      - PORT=3306
      - DATABASE=lei
      - REDIS_HOST=loveRedis:6379
      - REDIS_DATABASE=1
  loveDb:
    image: mariadb:10
    ports:
      - 3307:3306
    networks:
      - lovedb
    volumes:
      - /mnt/loveDb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=lei123
      - MYSQL_DATABASE=lei
    restart: always
    command: '--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
  loveRedis:
    image: redis:latest
    restart: always
    networks:
      - lovedb
    ports:
      - 6379:6379
networks:
  lovedb:
    driver: bridge