version: '3.7'

services:
  loveDb:
    image: mariadb:10
    ports:
      - 3307:3306
    volumes:
      - /mnt/loveDb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=lei123
      - MYSQL_DATABASE=lei
    restart: always
    command: '--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
  loveRedis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
  # jenkins:
  #   image: jenkinsci/blueocean
  #   restart: always
  #   ports:
  #     - 8080:8080
  #     - 50000:50000
  #   volumes:
  #     - /mnt/jenkins_home:/var/jenkins_home
  #     - /usr/bin/docker:/usr/bin/docker
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   user: root